FROM python
RUN pip install pipenv
WORKDIR /usr/src/app
COPY rest-gateway rest-gateway

WORKDIR /usr/src/app/rest-gateway
RUN pipenv install --system --deploy
RUN pip install gunicorn[gevent]

ARG PORT
EXPOSE $PORT
ENTRYPOINT scripts/start.sh
