version: '3.9'
services:
  rest-gateway:
    volumes:
      # VSCode
      - vscode-exts:/root/.vscode-server/extensions
      - vscode-exts-insiders:/root/.vscode-server-insiders/extensions
      # Github CLI
      - ~/.config/gh:/root/.config/gh
      # Kubernetes
      - /usr/local/bin/kubectl:/usr/local/bin/kubectl
      - ~/.kube/config:/root/.kube/config
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  vscode-exts:
  vscode-exts-insiders:
